import { foldForMatch } from "@/lib/text-fold";

// Yerel niyet verisi (docs/google-search-console-plan.md SC-F4, SO11): yakınlık
// belirteçleri ve yerleşik yer adları. Yalnız veri; eşleştirme intent.ts'te.
// Bu listenin dışındaki şehirler v1'de tanınmaz (kapsam dışı, docs).
// Bazı il adları başka dillerde sıradan sözcüktür ("van", "batman"); 81 ilin
// tamamı bilerek listede.

function folded(values: readonly string[]): string[] {
  return values.map((value) => foldForMatch(value).replace(/\s+/g, " ").trim());
}

export const LOCAL_MARKERS: readonly string[] = folded([
  "near me",
  "nearby",
  "close to me",
  "near",
  "yakınımda",
  "yakınımdaki",
  "en yakın",
  "yakın",
]);

// Türkiye'nin 81 ili.
const TURKISH_PROVINCES = [
  "Adana",
  "Adıyaman",
  "Afyonkarahisar",
  "Ağrı",
  "Amasya",
  "Ankara",
  "Antalya",
  "Artvin",
  "Aydın",
  "Balıkesir",
  "Bilecik",
  "Bingöl",
  "Bitlis",
  "Bolu",
  "Burdur",
  "Bursa",
  "Çanakkale",
  "Çankırı",
  "Çorum",
  "Denizli",
  "Diyarbakır",
  "Edirne",
  "Elazığ",
  "Erzincan",
  "Erzurum",
  "Eskişehir",
  "Gaziantep",
  "Giresun",
  "Gümüşhane",
  "Hakkari",
  "Hatay",
  "Isparta",
  "Mersin",
  "İstanbul",
  "İzmir",
  "Kars",
  "Kastamonu",
  "Kayseri",
  "Kırklareli",
  "Kırşehir",
  "Kocaeli",
  "Konya",
  "Kütahya",
  "Malatya",
  "Manisa",
  "Kahramanmaraş",
  "Mardin",
  "Muğla",
  "Muş",
  "Nevşehir",
  "Niğde",
  "Ordu",
  "Rize",
  "Sakarya",
  "Samsun",
  "Siirt",
  "Sinop",
  "Sivas",
  "Tekirdağ",
  "Tokat",
  "Trabzon",
  "Tunceli",
  "Şanlıurfa",
  "Uşak",
  "Van",
  "Yozgat",
  "Zonguldak",
  "Aksaray",
  "Bayburt",
  "Karaman",
  "Kırıkkale",
  "Batman",
  "Şırnak",
  "Bartın",
  "Ardahan",
  "Iğdır",
  "Yalova",
  "Karabük",
  "Kilis",
  "Osmaniye",
  "Düzce",
];

// Kuzey Makedonya'nın başlıca şehirleri (Latin yazımı).
const MACEDONIAN_CITIES = [
  "Skopje",
  "Skopie",
  "Bitola",
  "Ohrid",
  "Kumanovo",
  "Tetovo",
  "Prilep",
  "Strumica",
  "Veles",
  "Stip",
];

const WORLD_CITIES = [
  "London",
  "Paris",
  "Berlin",
  "Munich",
  "Hamburg",
  "Frankfurt",
  "Cologne",
  "Vienna",
  "Zurich",
  "Amsterdam",
  "Brussels",
  "Madrid",
  "Barcelona",
  "Rome",
  "Milan",
  "Prague",
  "Warsaw",
  "Budapest",
  "Athens",
  "Sofia",
  "Belgrade",
  "Moscow",
  "Dubai",
  "New York",
  "Los Angeles",
  "Chicago",
  "San Francisco",
  "Miami",
  "Toronto",
  "Sydney",
  "Melbourne",
  "Tokyo",
  "Singapore",
  "Hong Kong",
];

export const TURKISH_PROVINCE_COUNT = TURKISH_PROVINCES.length;

export const PLACE_NAMES: readonly string[] = Array.from(
  new Set(
    folded([...TURKISH_PROVINCES, ...MACEDONIAN_CITIES, ...WORLD_CITIES]),
  ),
);
