// Slice-2 UI copy: one flat table that mirrors design copy.md key for key.
// Pure and isomorphic (server messages import it too). Slice-1 pinned
// constants (CHANNEL_PICKER_COPY, WORK_HEADER_COPY, ...) stay where they are;
// workHeader.working lives there and is not repeated here.

export const WORKS_COPY = {
  "kit.tryAgain": "Try again",
  "kit.failed": "That didn't work. Try again.",
  "kit.stale": "This card is out of date. Refreshing.",
  "kit.workDone": "This Work is completed. Reopen it to continue.",
  "kit.chatBusy": "Wait for the reply to finish.",
  "kit.openCalendar": "Open calendar",
  "kit.fallbackTitle": "Shown in Works",
  "kit.fallbackBody": "This card belongs to a Work. Turn Works on to use it.",
  "kit.cancel": "Cancel",
  "kit.reasonRun": "Making your pieces…",
  "kit.showNewer": "Show the newer card",
  "kit.pending.plan": "Writing three directions…",
  "kit.pending.ideas": "Finding ideas…",
  "kit.pending.generic": "Working on it…",
  "planOptions.statusOpen": "Pick a direction",
  "planOptions.statusReplaced": "Replaced by a newer version",
  "planOptions.posts.one": "1 post",
  "planOptions.posts.many": "{n} posts",
  "planOptions.pick": "Use this direction",
  "planOptions.picking": "Building your plan…",
  "planOptions.startsWith": "Starts with: {topic}",
  "planOptions.allTopics": "See all {n} topics",
  "planOptions.footnote": "Not quite right? Tell me what to change.",
  "planOptions.tweak.playful": "More playful",
  "planOptions.tweak.educational": "More educational",
  "planOptions.tweak.shorter": "Shorter",
  "planOptions.basis": "Based on: {basis}",
  "planOptions.live.picked": "Plan ready: {label}.",
  "planOptions.alreadyPicked": "A direction was already picked for this plan.",
  "planOptions.replaced": "These directions were replaced by a newer card.",
  "planOptions.pickFailed": "Couldn't build the plan. Try again.",
  "planAlt.heading": "Other ideas",
  "planAlt.helper":
    "One quick request covers every post. Nothing changes until you pick an idea.",
  "planAlt.get": "Get other ideas",
  "planAlt.getting": "Thinking of other ideas…",
  "planAlt.refresh": "More ideas",
  "planAlt.use": "Use this idea",
  "planAlt.current": "Current idea",
  "planAlt.from": "From: {label}",
  "planAlt.readyFromOptions":
    "Ideas from the other directions are ready for each post.",
  "planAlt.post": "{day} · {channel}",
  "planAlt.locked": "Already made, so this idea can't change.",
  "planAlt.none": "No other idea fits this post yet.",
  "planAlt.nothingLeft": "Nothing to change: every post is already made.",
  "planAlt.swapped": "Idea swapped. You can switch back.",
  "planAlt.limit": "You've used both idea refreshes for this plan.",
  "planAlt.busy": "Other ideas are already being prepared.",
  "planAlt.mock":
    "Other ideas need the live AI model, which is switched off here.",
  "planAlt.failed": "Couldn't get other ideas. Try again.",
  "planAlt.stale": "That post changed. Refreshing.",
  "planAlt.live.ready": "Other ideas are ready.",
  "brand.heading": "Brand check",
  "brand.summary.one": "1 post needs a look",
  "brand.summary.many": "{n} posts need a look",
  "brand.flag.never": 'Mentions "{matched}" (your rule: {rule})',
  "brand.flag.preset": "Breaks your rule: {rule}",
  "brand.flag.figure": '"{matched}" isn\'t in your approved claims',
  "brand.flag.absolute": '"{matched}" is an absolute claim',
  "brand.chip.block": "Against a brand rule",
  "brand.chip.warn": "Worth a check",
  "brand.saveAnyway": "Save anyway",
  "brand.addAnyway": "Add anyway",
  "brand.blockedSave":
    'A brand rule stops this. Change the wording, or tap "Save anyway".',
  "brand.blockedSchedule":
    'A brand rule stops this. Tap "Add anyway" to go ahead.',
  "brand.checked": "Checked against {n} brand rules.",
  "brand.checkedNone":
    "No brand rules yet. Checked against the standard guardrails.",
  "brand.unavailable": "Brand rules couldn't be checked.",
  "brand.blockedNote": "These posts break a brand rule.",
  "ideaOptions.reasonDefault": "Ideas based on your brand profile.",
  "ideaOptions.titleDefault": "{n} ideas for {channels}",
  "ideaOptions.plan": "Plan it",
  "ideaOptions.where": "Where should it go?",
  "ideaOptions.suggested": "{when} suggested",
  "ideaOptions.otherTime": "Other time",
  "ideaOptions.add": "Add to calendar",
  "ideaOptions.addProduce": "Add & produce",
  "ideaOptions.addProduceCost": "Add & produce · {cost}",
  "ideaOptions.finding": "Finding a free day…",
  "ideaOptions.noSlot": "No free day in the next 60 days for {channel}.",
  "ideaOptions.scheduled": "On your calendar · {when}",
  "ideaOptions.added": "Added to your calendar.",
  "ideaOptions.already": "Already on your calendar.",
  "ideaOptions.noChannel": "Pick at least one channel.",
  "ideaOptions.gone": "This idea can't be scheduled any more.",
  "ideaOptions.live.time": "Time {i} of {n}: {when}",
  "ideaOptions.alreadyElsewhere": "Already on your calendar.",
  "slot.added": "Added to your calendar",
  "slot.produce": "Make post",
  "slot.changeTime": "Change time",
  "slot.confirmTime": "Save time",
  "slot.review": "Review",
  "slot.timeSaved": "Time updated.",
  "slot.where": "{when} · {where}",
  "slot.noFree": "No free time found. Pick a day in the calendar.",
  "slot.remove": "Remove",
  "slot.removeAsk": "Remove this from your calendar?",
  "slot.removeYes": "Remove",
  "slot.keep": "Keep it",
  "slot.removed": "Removed from your calendar.",
  "slot.removeLocked":
    "This piece already has content, so it can't be removed here.",
  "slot.zone": "Times in {zone}",
  "slot.cost": "Making it costs about {cost}.",
  "publish.review.scheduled": "If you approve, it goes out on or after {when}.",
  "publish.review.scheduledOff":
    "If you approve, it stays ready until you turn on scheduled posting.",
  "publish.review.nextSlot":
    "If you approve, it goes out at the next scheduled slot.",
  "publish.review.held":
    "If you approve, it waits on hold until you set a time.",
  "publish.review.manual":
    "You post this one yourself. Approving marks it ready.",
  "publish.review.locked":
    "{channel} isn't connected, so this can't post itself.",
  "publish.scheduled": "Goes out on or after {when}.",
  "publish.nextSlot": "Goes out at the next scheduled slot.",
  "publish.scheduledOff": "Planned for {when}, but scheduled posting is off.",
  "publish.turnOn": "Turn on scheduled posting",
  "publish.held": "On hold: no publish time is set.",
  "publish.heldPast": "On hold: its planned time has passed.",
  "publish.setTime": "Set a time",
  "publish.postNow": "Post now",
  "publish.manual": "Yours to post on {when}.",
  "publish.locked": "{channel} isn't connected yet.",
  "publish.connect": "Connect {channel}",
  "publish.published": "Published.",
  "publish.timeSaved": "Time updated.",
  "publish.publishing": "Posting to Instagram…",
  "publish.failed": "Couldn't post to Instagram.",
  "publish.failedWhy": "Couldn't post to Instagram: {reason}",
  "publish.postConfirm": "Post to Instagram now? It goes live right away.",
  "publish.postIt": "Post it",
  "publish.postSent": "Sent to Instagram. It goes live in a moment.",
  "publish.alreadyPosting": "This piece is already being posted.",
  "publish.notReady": "Approve this piece before posting it.",
  "journey.approve.label": "Approve {n}",
  "journey.approve.title": "{n} pieces are ready. Approve them in one go.",
  "journey.approve.done": "{approved} approved.",
  "journey.approve.doneHeld":
    "{approved} approved. {held} on hold until you set a time.",
  "journey.approve.doneFailed": "{approved} approved, {failed} could not be.",
  "journey.approve.changed": "{n} more pieces are ready. Review them first.",
  "journey.approve.locked": "{n} skipped: their Work is completed.",
  "workHeader.channelsDialogTitle": "Channels for this Work",
  "workHeader.channelsDialogNote":
    "Pieces you already made stay where they are.",
  "workHeader.channelsSaved": "Channels updated.",
  "workHeader.deleteConfirm":
    "Delete this Work and its conversation? Pieces already made stay in your library.",
  "workDelete.blocked":
    "This Work still has pieces on your calendar. Archive it instead.",
  "workToday.locked":
    "Today's brief can't be completed, archived, renamed or deleted.",
  "starter.planWeek.reason":
    "Pick one of three directions for a week of {named} content.",
  "starter.ideas.reason":
    "Three ideas for {named}, written from your brand profile.",
  "starter.makePost.reason":
    "One piece for {channel}, put on your calendar first.",
  "starter.planWeek.visible": "Plan the week · from {when}",
  "starter.aiOff.title": "AI is switched off here",
  "starter.aiOff.reason": "AI features are turned off for this workspace.",
  "plan.stale": "Some days in this plan have passed. Ask me to plan again.",
  "plan.again": "Plan again",
  "plan.savedToast": "Plan saved ({n} posts).",
  "plan.producing": "This plan is already being produced.",
  "plan.saving": "Already being saved.",
  "plan.notFound": "Plan not found.",
  "plan.costNote": "Making the first week costs about {cost} in pictures.",
  "plan.summary.auto": "{n} on Instagram, posted once approved",
  "plan.summary.manual": "{n} you post yourself",
  "plan.summary.approval": "{n} waiting for your approval",
  "plan.tone.auto": "Posts to Instagram once you approve it",
  "plan.tone.manual": "You post it yourself",
  "plan.tone.approval": "Waits for your approval",
  "msg.workInactive": "This Work is completed. Reopen it to continue.",
  "msg.rate": "Slow down for a moment.",
  "a11y.directions": "Plan directions",
  "a11y.option": "Direction: {label}",
  "a11y.channels": "Channels",
  "a11y.otherIdeas": "Other ideas for {post}",
  "a11y.otherTime": "Show another suggested time",
  "a11y.enlarge": "Enlarge visual {i} of {n}",
  "a11y.cardUpdated": "Card updated.",
  "master.statusDraft": "Draft",
  "master.statusAdapted": "Adapted",
  "master.statusReplaced": "Replaced by a newer version",
  "master.messageLabel": "Main message",
  "master.channelsLabel": "Channels",
  "master.adapt": "Adapt to channels",
  "master.adapting": "Adapting…",
  "master.readapt": "Re-adapt",
  "master.schedule": "Add to calendar",
  "master.scheduleMake": "Add & make",
  "master.chip.add": "+ Add",
  "master.chip.connect": "Connect",
  "master.chip.locked": "Publishing locked",
  "master.chip.website": "Website",
  "master.noTargets": "Tick at least one channel.",
  "master.issues": "Worth a check",
  "master.adaptFailed": "Couldn't adapt the message. Try again.",
  "master.adaptLimit":
    "This message was already adapted three times. Add it to the calendar as it is.",
  "master.channelOutside": "That channel is not part of this work.",
  "master.adaptMock":
    "Adapting needs the live AI model, which is switched off here. You can still add the message to the calendar as it is.",
  "master.adaptBusy": "Already adapting in another tab.",
  "master.checkAgain": "Check again",
  "master.panelNote": "All channels are planned for this time.",
  "master.scheduled": "Added to your calendar.",
  "variants.use": "Use this one",
  "variants.current": "Current",
  "variants.pickBefore":
    "Pick before approving. Once approved, the picture is locked.",
  "variants.adopted": "Picture updated.",
  "variants.locked":
    "Approved, so the picture can't change. Ask for a change instead.",
  "variants.failed": "Couldn't make the visuals. Try again.",
  "variants.alt": "Visual {i} of {n}",
  "variants.useAria": "Use visual {i} of {n}",
  "brief.heading": "Today",
  "brief.summary.some": "{n} things for today",
  "brief.summary.one": "1 thing for today",
  "brief.summary.none": "Nothing is scheduled for today.",
  "brief.group.content": "Content",
  "brief.group.seo": "SEO",
  "brief.group.ads": "Ads",
  "brief.plan": "Plan today",
  "brief.planWeek": "Plan the week",
  "brief.connectFirst": "Connect a channel",
  "brief.next": "Next",
  "brief.nextCost": "{label} · {cost}",
  "brief.rowOpen": "Open",
  "brief.rowReview": "Review",
  "brief.performance": "Check performance",
  "brief.connectAnalytics": "Connect analytics",
  "brief.yesterday": "Yesterday: {published} published, {failed} failed.",
  "brief.yesterdayNone": "Yesterday: nothing went out.",
  "brief.focus": "Focus: {title}",
  "brief.connectAction": "Connect",
  "brief.startAction": "Start",
  "brief.connectRow": "Connect a channel to publish automatically",
  "brief.ideasRow": "{n} ideas worth a look",
  "brief.channelRow": "{channel} is connected. Start a Work for it",
  "brief.more": "+{n} more",
  "today.jump": "Today's brief",
  "today.opening": "Opening today's brief…",
  "today.openToday": "Open today",
  "ads.heading": "Meta Ads",
  "ads.chip.cpl": "CPL",
  "ads.chip.costPer": "Cost / {label}",
  "ads.chip.change": "{pct} vs last check",
  "ads.chip.suggested": "Suggested {amount} / day",
  "ads.headline": "{campaign}: cost per {label} is {cost}",
  "ads.budgetApproval": "Review budget change",
  "ads.raise": "Raise the daily budget from {from} to {to}",
  "ads.lower": "Lower the daily budget from {from} to {to}",
  "ads.change": "Change the daily budget (waiting for your approval)",
  "ads.approveSpend": "Approve spend",
  "ads.pause": "Pause this campaign (waiting for your approval)",
  "ads.pauseReview": "Review pause",
  "ads.approvePause": "Approve pause",
  "ads.dismissed": "Dismissed. It may come back after the next check.",
  "ads.check": "Check performance",
  "ads.checking": "Checking…",
  "ads.checked": "Checked just now.",
  "ads.approved": "Approved.",
  "ads.preview": "Preview campaign",
  "ads.open": "Open Ads Manager",
  "ads.state.needsConnect":
    "Connect Meta Ads to see cost per lead and budget suggestions.",
  "ads.connect": "Connect Meta Ads",
  "ads.state.needsAccount":
    "Meta Ads is connected, but no ad account is selected.",
  "ads.pickAccount": "Pick an ad account",
  "ads.state.noData":
    "The first check runs within a few hours. You can check now.",
  "ads.state.nothing":
    "No active campaign with spend and a daily budget in the last 7 days. Campaigns with a lifetime budget aren't checked.",
  "ads.state.stale": "These numbers are from {date} and may be out of date.",
  "ads.reconnect": "Reconnect Meta Ads",
  "ads.asOf": "As of {date}",
  "ads.changed":
    "The budget changed since this was proposed. Dismiss it; a new suggestion can follow the next check.",
  "ads.dismiss": "Dismiss",
  "ads.failed": "Couldn't read Meta Ads. Try again.",
  "ads.pauseAll": "Pause all",
  "ads.alerts": "Ad alerts",
  "ads.pauseAllConfirm": "Pause {n} campaign(s)",
  "ads.pausedAll": "Paused {n} campaign(s).",
  "ads.pausedNothing": "Nothing was running.",
  "ads.cancel": "Cancel",
  "cta.connected": "{channel} is connected.",
  "cta.open": "Open a Work for {channel}",
  "cta.opening": "Opening…",
  "cta.failed": "Couldn't open a Work. Try again.",
  "cta.back": "Back to {title}",
  "cta.backGeneric": "Back to your Work",
} as const;

export type CopyKey = keyof typeof WORKS_COPY;

/** Replaces every {name} with String(values[name]); an unknown placeholder stays as written. */
export function copyText(
  key: CopyKey,
  values?: Readonly<Record<string, string | number>>,
): string {
  const text: string = WORKS_COPY[key];
  if (!values) return text;
  return text.replace(/\{([A-Za-z0-9_]+)\}/g, (whole, name: string) =>
    Object.prototype.hasOwnProperty.call(values, name)
      ? String(values[name])
      : whole,
  );
}

/** The quiet brand-check line: rule count, "no rules yet", or the failure line. */
export function brandCheckText(
  check: { state: "checked"; rules: number } | { state: "skipped" },
): string {
  if (check.state === "skipped") return copyText("brand.unavailable");
  return check.rules > 0
    ? copyText("brand.checked", { n: check.rules })
    : copyText("brand.checkedNone");
}
