// Pure rules for plan slot alternatives: swap, normalisation, and which slots may change.
import { foldForMatch } from "@/lib/text-fold";

export const PLAN_ALTERNATIVES_PER_SLOT = 2;
export const MAX_ALTERNATIVE_SLOTS_PER_RUN = 14;
export const MAX_ALTERNATIVE_RUNS = 2;
export const ALTERNATIVES_CLAIM_TTL_MS = 120_000;
// 2 that came with the pick from the other directions + 2 generated by More ideas.
export const MAX_ALTERNATIVES_STORED = 4;

const MAX_FROM_LENGTH = 40;

export type PlanAlternative = {
  topic: string;
  captionIdea: string;
  /** Label of the direction the idea came from; absent for generated ones. */
  from?: string;
  /**
   * The pool idea this text came from: a pool post that was swapped away keeps
   * its idea link here (and the slot's idea origin that named it), so the idea
   * is neither consumed, judged nor shown as scheduled for a post that no
   * longer uses it, and swapping back restores both.
   */
  ideaId?: string;
  origin?: IdeaOrigin;
};

type IdeaOrigin = { kind: "idea"; ref: string };

type SwappableItem = {
  topic: string;
  captionIdea: string;
  from?: string;
  ideaId?: string;
  origin?: unknown;
  alternatives?: PlanAlternative[];
};

// The slot's origin when it names the very idea the slot is linked to.
function ideaOriginOf(item: SwappableItem): IdeaOrigin | undefined {
  const origin = item.origin as { kind?: unknown; ref?: unknown } | undefined;
  return item.ideaId &&
    origin?.kind === "idea" &&
    origin.ref === item.ideaId
    ? { kind: "idea", ref: item.ideaId }
    : undefined;
}

function alt(
  topic: string,
  captionIdea: string,
  from: string | undefined,
  ideaId?: string,
  origin?: IdeaOrigin,
): PlanAlternative {
  return {
    topic,
    captionIdea,
    ...(from ? { from } : {}),
    ...(ideaId ? { ideaId } : {}),
    ...(ideaId && origin ? { origin } : {}),
  };
}

/**
 * Swaps the item's idea with alternatives[altIndex]. The displaced idea takes the
 * SAME alternatives index (with the item's label, its pool idea link and the
 * idea origin that named that idea), so a second swap restores all of them. Any
 * other origin (a master, a brief, a creative: the slot's identity for
 * schedule-slots) stays with the slot. The caller recomputes brand flags (they
 * are dropped here).
 */
export function swapItem<T extends SwappableItem>(item: T, altIndex: number): T | null {
  const list = item.alternatives ?? [];
  const chosen = Number.isInteger(altIndex) && altIndex >= 0 ? list[altIndex] : undefined;
  if (!chosen) return null;
  const next: Record<string, unknown> = { ...item };
  const ideaOrigin = ideaOriginOf(item);
  delete next.brandFlags;
  delete next.from;
  delete next.ideaId;
  if (ideaOrigin) delete next.origin;
  if (chosen.from) next.from = chosen.from;
  if (chosen.ideaId) {
    next.ideaId = chosen.ideaId;
    if (chosen.origin && next.origin === undefined) next.origin = chosen.origin;
  }
  next.topic = chosen.topic;
  next.captionIdea = chosen.captionIdea;
  next.alternatives = list.map((a, i) =>
    i === altIndex
      ? alt(item.topic, item.captionIdea, item.from, item.ideaId, ideaOrigin)
      : a,
  );
  return next as T;
}

export type SwapSlotState = {
  status: string;
  hasVersion: boolean;
  liveTask: boolean;
  inRunningClaim: boolean;
} | null;

export type SwapCheck =
  | { ok: true }
  | { ok: false; code: "SUPERSEDED" | "LOCKED"; message: string };

const LOCKED_MESSAGE = "Already made, so this idea can't change.";

export function canSwapSlot(
  cardState: "draft" | "saved" | "superseded",
  slot: SwapSlotState,
): SwapCheck {
  if (cardState === "superseded") {
    return { ok: false, code: "SUPERSEDED", message: "This plan was replaced by a newer one." };
  }
  if (cardState === "draft") return { ok: true };
  if (!slot || slot.status !== "DRAFT" || slot.hasVersion || slot.liveTask || slot.inRunningClaim) {
    return { ok: false, code: "LOCKED", message: LOCKED_MESSAGE };
  }
  return { ok: true };
}

/**
 * Cleans a batch of generated alternatives: trims, drops empties and duplicates
 * (diacritic/case-insensitive) of the current idea, each other, taken topics and
 * the existing alternatives; returns only NEW ones within the per-run and stored caps.
 */
export function normalizeAlternatives(
  raw: readonly PlanAlternative[],
  current: PlanAlternative,
  takenTopics: readonly string[],
  existing: readonly PlanAlternative[] = [],
): PlanAlternative[] {
  const seen = new Set<string>();
  seen.add(foldForMatch(current.topic.trim()));
  for (const t of takenTopics) seen.add(foldForMatch(t.trim()));
  for (const e of existing) seen.add(foldForMatch(e.topic.trim()));

  const room = Math.max(0, MAX_ALTERNATIVES_STORED - existing.length);
  const limit = Math.min(PLAN_ALTERNATIVES_PER_SLOT, room);
  const out: PlanAlternative[] = [];
  for (const r of raw) {
    if (out.length >= limit) break;
    const topic = (r.topic ?? "").trim();
    const captionIdea = (r.captionIdea ?? "").trim();
    if (!topic || !captionIdea) continue;
    const key = foldForMatch(topic);
    if (!key || seen.has(key)) continue;
    seen.add(key);
    const from = r.from?.trim().slice(0, MAX_FROM_LENGTH);
    out.push(alt(topic, captionIdea, from || undefined));
  }
  return out;
}

/**
 * The other directions' idea for this slot, in option order, labelled with their
 * direction, so picking one direction keeps the ideas of the rest.
 */
export function alternativesFromOptions(
  options: readonly { label: string; ideas: readonly PlanAlternative[] }[],
  pickedIndex: number,
  slotIndex: number,
): PlanAlternative[] {
  const out: PlanAlternative[] = [];
  options.forEach((option, i) => {
    if (i === pickedIndex) return;
    const idea = option.ideas[slotIndex];
    if (!idea) return;
    const topic = idea.topic?.trim();
    const captionIdea = idea.captionIdea?.trim();
    if (!topic || !captionIdea) return;
    out.push(alt(topic, captionIdea, option.label.trim().slice(0, MAX_FROM_LENGTH) || undefined));
  });
  return out.slice(0, MAX_ALTERNATIVES_STORED);
}

/**
 * Indexes whose idea can change and that have something to swap to.
 * slotStates null = a draft card (every slot is free); otherwise the saved card's
 * per-index Creative state.
 */
export function swappableIndexes(
  items: readonly { alternatives?: readonly PlanAlternative[] }[],
  slotStates: readonly SwapSlotState[] | null,
): number[] {
  const out: number[] = [];
  items.forEach((item, i) => {
    if (!item.alternatives || item.alternatives.length === 0) return;
    const check = slotStates
      ? canSwapSlot("saved", slotStates[i] ?? null)
      : canSwapSlot("draft", null);
    if (check.ok) out.push(i);
  });
  return out;
}
