import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms that govern your use of the Agentelse product.",
};

const LAST_UPDATED = "August 20, 2026";

type TermsSection = {
  id: string;
  title: string;
  body: React.ReactNode;
};

const SECTIONS: TermsSection[] = [
  {
    id: "agreement",
    title: "Agreement to these terms",
    body: (
      <p>
        These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and
        use of the Agentelse product at agentelse.ai (the
        &ldquo;Service&rdquo;). By accessing or using the Service, you agree to
        be bound by these Terms. If you don&rsquo;t agree, don&rsquo;t use the
        Service.
      </p>
    ),
  },
  {
    id: "the-service",
    title: "The service",
    body: (
      <p>
        Agentelse is an AI-powered platform that researches your market,
        discovers opportunities, and coordinates specialized AI teams to plan
        and, where you&rsquo;ve granted permission, execute growth work across
        your connected tools.
      </p>
    ),
  },
  {
    id: "accounts",
    title: "Accounts",
    body: (
      <p>
        You must provide accurate information when creating an account and keep
        it up to date. You&rsquo;re responsible for safeguarding your login
        credentials and for all activity under your account. You must be
        authorized to act on behalf of your company to accept these Terms and
        connect its tools to Agentelse.
      </p>
    ),
  },
  {
    id: "human-control",
    title: "Human control and approvals",
    body: (
      <p>
        Every capability Agentelse has is gated by the permission level you set:
        view, create, recommend, request approval, or execute. You are
        responsible for the permission levels you grant and for reviewing any
        action routed to you for approval before it happens. Agentelse will not
        take an action beyond the permission level you&rsquo;ve configured for
        it.
      </p>
    ),
  },
  {
    id: "acceptable-use",
    title: "Acceptable use",
    body: (
      <>
        <p>You agree not to use the Service to:</p>
        <ul className="flex flex-col gap-2 pl-5 list-disc">
          <li>Violate any applicable law or regulation.</li>
          <li>
            Infringe the intellectual property or other rights of any third
            party.
          </li>
          <li>
            Distribute malware, or attempt to gain unauthorized access to the
            Service or its underlying systems.
          </li>
          <li>
            Reverse engineer or attempt to extract the source code of the
            Service, except where permitted by law.
          </li>
          <li>
            Resell or provide access to the Service to third parties without our
            authorization.
          </li>
          <li>Generate content that is deceptive, harassing, or unlawful.</li>
        </ul>
      </>
    ),
  },
  {
    id: "connected-accounts",
    title: "Connected third-party accounts",
    body: (
      <p>
        You may authorize Agentelse to access third-party tools, such as
        analytics, advertising, CRM, or social accounts, within the scopes you
        grant. You&rsquo;re responsible for complying with those third
        parties&rsquo; own terms of use. You can revoke a connection at any time
        from your workspace settings.
      </p>
    ),
  },
  {
    id: "ai-outputs",
    title: "AI-generated content and outputs",
    body: (
      <p>
        Research, recommendations, drafts, and actions generated by Agentelse
        are produced by AI and may contain errors or inaccuracies. You&rsquo;re
        responsible for reviewing outputs before relying on, publishing, or
        executing them — particularly anything not routed through an approval
        step you control.
      </p>
    ),
  },
  {
    id: "fees",
    title: "Fees and billing",
    body: (
      <p>
        Fees for paid plans are described on our{" "}
        <a
          href="https://agentelse.com/pricing"
          className="underline underline-offset-4"
        >
          Pricing
        </a>{" "}
        page and are based on your selected plan and usage. Fees are
        non-refundable except where required by law. We may change our pricing,
        and will provide reasonable notice before any change takes effect for
        your account.
      </p>
    ),
  },
  {
    id: "intellectual-property",
    title: "Intellectual property",
    body: (
      <p>
        Agentelse and its licensors retain all rights, title, and interest in
        the Service, including its software, design, and underlying technology.
        As between you and Agentelse, you retain ownership of your company data
        and the content created within your workspace, subject to the rights of
        any underlying third-party providers whose tools you&rsquo;ve connected.
      </p>
    ),
  },
  {
    id: "confidentiality",
    title: "Confidentiality and data ownership",
    body: (
      <p>
        Your company data belongs to you. We handle it in accordance with our{" "}
        <Link href="/privacy" className="underline underline-offset-4">
          Privacy Policy
        </Link>{" "}
        and the data-separation and permission principles described on our{" "}
        <a
          href="https://agentelse.com/security"
          className="underline underline-offset-4"
        >
          Security
        </a>{" "}
        page.
      </p>
    ),
  },
  {
    id: "disclaimers",
    title: "Disclaimers",
    body: (
      <p>
        The Service is provided &ldquo;as is&rdquo; and &ldquo;as
        available,&rdquo; without warranties of any kind, whether express or
        implied. We don&rsquo;t warrant that the Service will be uninterrupted,
        error-free, or that AI-generated outputs will be accurate or fit for any
        particular purpose.
      </p>
    ),
  },
  {
    id: "limitation-of-liability",
    title: "Limitation of liability",
    body: (
      <p>
        To the maximum extent permitted by applicable law, Agentelse will not be
        liable for any indirect, incidental, special, consequential, or punitive
        damages, or for lost profits or data, arising from your use of the
        Service. Our aggregate liability for any claim arising out of these
        Terms will not exceed the amount you paid us for the Service in the
        twelve months preceding the claim.
      </p>
    ),
  },
  {
    id: "indemnification",
    title: "Indemnification",
    body: (
      <p>
        You agree to indemnify and hold Agentelse harmless from any claims,
        damages, or expenses arising from your use of the Service, your
        violation of these Terms, or your violation of any law or third-party
        right.
      </p>
    ),
  },
  {
    id: "termination",
    title: "Termination",
    body: (
      <p>
        You may stop using the Service and close your account at any time. We
        may suspend or terminate your access if you violate these Terms or if
        required by law. Upon termination, your right to use the Service ends,
        and your data will be handled in accordance with our{" "}
        <Link href="/privacy" className="underline underline-offset-4">
          Privacy Policy
        </Link>
        .
      </p>
    ),
  },
  {
    id: "changes",
    title: "Changes to these terms",
    body: (
      <p>
        We may update these Terms from time to time. If we make material
        changes, we will update the &ldquo;Last updated&rdquo; date below and,
        where appropriate, provide additional notice. Continued use of the
        Service after a change takes effect constitutes acceptance of the
        revised Terms.
      </p>
    ),
  },
  {
    id: "governing-law",
    title: "Governing law and disputes",
    body: (
      <p>
        These Terms are governed by applicable law, without regard to
        conflict-of-laws principles. If a dispute arises, the parties agree to
        first attempt to resolve it through good-faith negotiation; if that
        fails, either party may pursue any remedy available under applicable law
        before a court of competent jurisdiction.
      </p>
    ),
  },
  {
    id: "contact",
    title: "Contact us",
    body: (
      <p>
        Questions about these Terms? Reach us at{" "}
        <a
          href="mailto:hello@agentelse.ai"
          className="underline underline-offset-4"
        >
          hello@agentelse.ai
        </a>
        .
      </p>
    ),
  },
];

export default function TermsPage() {
  return (
    <div className="flex min-h-screen w-full flex-col bg-background">
      <header className="border-b border-border">
        <div className="mx-auto flex w-full max-w-3xl items-center justify-between px-6 py-5">
          <Link href="/login" className="flex items-center">
            <img src="/logo.png" alt="Agentelse" className="h-6 w-auto" />
          </Link>
          <Link
            href="/login"
            className="text-sm text-muted-foreground transition-colors hover:text-foreground"
          >
            Sign in
          </Link>
        </div>
      </header>

      <main className="mx-auto w-full max-w-3xl flex-1 px-6 py-16">
        <div className="flex flex-col gap-4">
          <p className="text-sm font-medium tracking-wide text-muted-foreground uppercase">
            Legal
          </p>
          <h1 className="text-3xl font-semibold tracking-tight text-balance xl:text-4xl">
            Terms of Service
          </h1>
          <p className="max-w-[60ch] text-base text-pretty text-muted-foreground">
            The terms that govern your use of the Agentelse product.
          </p>
          <p className="text-sm text-muted-foreground">
            Last updated: {LAST_UPDATED}
          </p>
        </div>

        <div className="mt-12 flex flex-col divide-y divide-border border-t border-border">
          {SECTIONS.map((section) => (
            <div
              key={section.id}
              id={section.id}
              className="flex flex-col gap-3 py-8 scroll-mt-24"
            >
              <h2 className="text-xl font-semibold tracking-tight text-foreground">
                {section.title}
              </h2>
              <div className="flex flex-col gap-3 text-sm leading-relaxed text-muted-foreground">
                {section.body}
              </div>
            </div>
          ))}
        </div>
      </main>

      <footer className="border-t border-border">
        <div className="mx-auto flex w-full max-w-3xl flex-col-reverse items-start gap-2 px-6 py-6 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between">
          <span>© {new Date().getFullYear()} Agentelse</span>
          <div className="flex gap-4">
            <Link
              href="/privacy"
              className="transition-colors hover:text-foreground"
            >
              Privacy
            </Link>
            <Link
              href="/terms"
              className="transition-colors hover:text-foreground"
            >
              Terms
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
