import { readFile } from "node:fs/promises";
import path from "node:path";

import { NextResponse } from "next/server";

import { prisma } from "@/lib/prisma";
import {
  requireUser,
  requireProjectAccess,
} from "@/server/security/tenant-context";
import { isAgentelseError } from "@/server/security/errors";

// Serves locally-generated/uploaded assets (creative images from
// openclaw-image-client.ts, logo uploads/generations from
// project-actions.ts) — there is no S3/R2 storage layer in this codebase, so
// `local-asset://` storageKeys point into storage/assets/ on this machine's
// disk.
const LOCAL_ASSET_SCHEME = "local-asset://";
const LOCAL_ASSETS_DIR = path.join(process.cwd(), "storage", "assets");
// Filenames are always generated by us as `${randomUUID()}.<ext>` — reject
// anything else outright rather than resolving it against the filesystem.
// Uzantı listesi sohbet eklerini de kapsar (command-actions.ts CHAT_MIME_TO_EXT).
const SAFE_FILENAME = /^[a-zA-Z0-9-]+\.(png|jpe?g|webp|pdf|txt|csv|md)$/;

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ assetId: string }> },
) {
  const { assetId } = await params;

  let userId: string;
  try {
    ({ userId } = await requireUser());
  } catch {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const asset = await prisma.asset.findUnique({ where: { id: assetId } });
  if (!asset) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  try {
    await requireProjectAccess(userId, asset.projectId);
  } catch (error) {
    if (isAgentelseError(error)) {
      return NextResponse.json({ error: "Not found" }, { status: 404 });
    }
    throw error;
  }

  if (!asset.storageKey.startsWith(LOCAL_ASSET_SCHEME)) {
    return NextResponse.json(
      { error: "Asset has no locally-servable file" },
      { status: 404 },
    );
  }

  const filename = asset.storageKey.slice(LOCAL_ASSET_SCHEME.length);
  if (!SAFE_FILENAME.test(filename)) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  try {
    const file = await readFile(path.join(LOCAL_ASSETS_DIR, filename));
    return new NextResponse(new Uint8Array(file), {
      headers: {
        "Content-Type": asset.mimeType,
        "Cache-Control": "private, max-age=31536000, immutable",
      },
    });
  } catch {
    return NextResponse.json({ error: "File not found" }, { status: 404 });
  }
}
