-- Gemini sistemden kaldırıldı; geçmiş kayıtlarda kalan sağlayıcı/model etiketleri
-- ve hata metinleri nötr adlara çevrilir. Yalnızca sistemin kendi yazdığı etiket
-- ve hata sütunlarına dokunulur; kullanıcı içeriği (marka metinleri, üretilen
-- yazılar) değiştirilmez. Her ifade tekrar çalıştırılabilir (eşleşme yoksa no-op).

-- Reasoning çağrıları: model adı ve hata metni
UPDATE "ReasoningCall"
SET "model" = 'legacy-model'
WHERE "model" ILIKE '%gemini%';

UPDATE "ReasoningCall"
SET "errorMessage" = regexp_replace("errorMessage", 'gemini[A-Za-z0-9_.-]*', 'legacy', 'gi')
WHERE "errorMessage" ILIKE '%gemini%';

-- Reasoning denetim kayıtlarındaki model adı (metadata.model)
UPDATE "AuditLog"
SET "metadata" = jsonb_set("metadata", '{model}', '"legacy-model"')
WHERE "action" LIKE 'reasoning.%'
  AND jsonb_typeof("metadata"->'model') = 'string'
  AND "metadata"->>'model' ILIKE '%gemini%';

-- Yürütme işleri: eski sağlayıcı anahtarı ("gemini-ai", "gemini-creative") ve hata metni
UPDATE "ExecutionJob"
SET "providerId" = 'legacy-' || substring("providerId" from 8)
WHERE "providerId" ILIKE 'gemini-%';

UPDATE "ExecutionJob"
SET "errorMessage" = regexp_replace("errorMessage", 'gemini[A-Za-z0-9_.-]*', 'legacy', 'gi')
WHERE "errorMessage" ILIKE '%gemini%';

-- Sağlayıcı tanımı: kayıttan çıkan sağlayıcının satırı; sağlık ve olay kayıtları
-- ProviderDefinition silinince ON DELETE CASCADE ile birlikte gider.
DELETE FROM "ProviderDefinition"
WHERE "key" ILIKE '%gemini%' OR "name" ILIKE '%gemini%';

-- Kreatif sürümleri: "Generated by" etiketi
UPDATE "CreativeVersion"
SET "generationProvider" = 'legacy'
WHERE lower("generationProvider") = 'gemini';

UPDATE "CreativeVersion"
SET "generationProvider" = 'legacy-' || substring("generationProvider" from 8)
WHERE "generationProvider" ILIKE 'gemini-%';

-- Başarısız iş / tetikleyici / kurulum adımı hata metinleri
UPDATE "DeadLetterJob"
SET "reason" = regexp_replace("reason", 'gemini[A-Za-z0-9_.-]*', 'legacy', 'gi')
WHERE "reason" ILIKE '%gemini%';

UPDATE "DeadLetterJob"
SET "lastError" = regexp_replace("lastError", 'gemini[A-Za-z0-9_.-]*', 'legacy', 'gi')
WHERE "lastError" ILIKE '%gemini%';

UPDATE "AgencyTrigger"
SET "error" = regexp_replace("error", 'gemini[A-Za-z0-9_.-]*', 'legacy', 'gi')
WHERE "error" ILIKE '%gemini%';

UPDATE "ProjectSetupStageRecord"
SET "error" = regexp_replace("error", 'gemini[A-Za-z0-9_.-]*', 'legacy', 'gi')
WHERE "error" ILIKE '%gemini%';
