-- CreateEnum
CREATE TYPE "SetupStage" AS ENUM ('INTAKE', 'DEEP_DISCOVERY', 'BRAND_CONSTITUTION', 'SIGNAL_PROFILE', 'BASELINE_AUDITS', 'GOAL_GENERATION', 'AGENCY_CONFIGURATION', 'AUTONOMY_CONFIGURATION', 'INITIAL_OPPORTUNITIES', 'INITIAL_IDEA_PORTFOLIO', 'INITIAL_WORK_PLAN', 'PROJECT_ACTIVATION');

-- CreateEnum
CREATE TYPE "SetupStageStatus" AS ENUM ('PENDING', 'RUNNING', 'WAITING_CLIENT', 'COMPLETED', 'FAILED', 'SKIPPED');

-- CreateEnum
CREATE TYPE "FactClassification" AS ENUM ('VERIFIED_FACT', 'LIKELY_FACT', 'ASSUMPTION', 'CONTRADICTION', 'UNKNOWN', 'RECOMMENDATION');

-- CreateEnum
CREATE TYPE "SignalCategory" AS ENUM ('COMPETITOR', 'PRODUCT_LAUNCH', 'TECHNOLOGY', 'SEO', 'SOCIAL_TREND', 'PAID_ADVERTISING', 'MEDIA', 'CREATOR', 'PARTNERSHIP', 'EVENT', 'OFFLINE', 'CUSTOMER', 'MARKET', 'CULTURE', 'PERFORMANCE', 'OTHER');

-- CreateEnum
CREATE TYPE "SignalIntensity" AS ENUM ('VERY_HIGH', 'HIGH', 'MEDIUM', 'LOW', 'OFF');

-- CreateEnum
CREATE TYPE "SignalStatus" AS ENUM ('NEW', 'SCORED', 'PROMOTED', 'DISCARDED', 'DUPLICATE');

-- CreateEnum
CREATE TYPE "FindingSourceType" AS ENUM ('RESEARCH_TASK', 'SIGNAL', 'AUDIT', 'CLIENT_INPUT', 'LEARNING');

-- CreateEnum
CREATE TYPE "InsightStatus" AS ENUM ('NEW', 'EVALUATED', 'PROMOTED', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "IdeaStatus" AS ENUM ('RAW', 'RESEARCHING', 'VALIDATED', 'CONCEPT', 'SHORTLISTED', 'APPROVED', 'PLANNING', 'ACTIVE', 'MEASURING', 'LEARNED', 'ARCHIVED', 'REJECTED');

-- CreateEnum
CREATE TYPE "CreativeLens" AS ENUM ('BRAND', 'CULTURE', 'PR', 'SOCIAL', 'PRODUCT', 'GROWTH', 'PARTNERSHIP', 'CREATOR', 'MEDIA', 'COMMUNITY', 'TECHNOLOGY', 'EXPERIENCE', 'OFFLINE', 'CONTENT', 'UTILITY', 'DATA');

-- CreateEnum
CREATE TYPE "CouncilType" AS ENUM ('STRATEGY', 'CREATIVE', 'GROWTH', 'MEDIA', 'RISK');

-- CreateEnum
CREATE TYPE "CouncilRecommendation" AS ENUM ('STRONG_APPROVE', 'APPROVE', 'REVISE', 'REJECT');

-- CreateEnum
CREATE TYPE "AgencyDecisionType" AS ENUM ('REJECT', 'BACKLOG', 'RESEARCH_MORE', 'CREATE_EXPERIMENT', 'CREATE_CAMPAIGN', 'CREATE_TASK', 'CREATE_MULTI_DEPARTMENT_PLAN');

-- CreateEnum
CREATE TYPE "AgencyDecisionSubject" AS ENUM ('OPPORTUNITY', 'IDEA', 'HANDOFF', 'TRIGGER');

-- CreateEnum
CREATE TYPE "DepartmentKey" AS ENUM ('BRAND_STRATEGY', 'MARKET_INTELLIGENCE', 'CUSTOMER_INTELLIGENCE', 'COMPETITOR_INTELLIGENCE', 'CREATIVE', 'ART_DIRECTION', 'COPY_CONTENT', 'SOCIAL_MEDIA', 'SEO', 'PERFORMANCE_MARKETING', 'DATA_ANALYTICS', 'GROWTH', 'PR_MEDIA', 'INFLUENCER_CREATOR', 'PARTNERSHIPS', 'CRM_LIFECYCLE', 'WEB_PRODUCT', 'EVENTS', 'OFFLINE_MEDIA');

-- CreateEnum
CREATE TYPE "DepartmentMode" AS ENUM ('OFF', 'LISTEN', 'SUGGEST', 'PREPARE', 'EXECUTE');

-- CreateEnum
CREATE TYPE "WorkPlanType" AS ENUM ('SINGLE_TASK', 'EXPERIMENT', 'CAMPAIGN', 'MULTI_DEPARTMENT');

-- CreateEnum
CREATE TYPE "WorkPlanStatus" AS ENUM ('DRAFT', 'AWAITING_APPROVAL', 'APPROVED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'FAILED');

-- CreateEnum
CREATE TYPE "WorkHandoffStatus" AS ENUM ('PROPOSED', 'ACCEPTED', 'TASK_CREATED', 'COMPLETED', 'REJECTED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "ProjectGoalStatus" AS ENUM ('PROPOSED', 'APPROVED', 'ACTIVE', 'PAUSED', 'ACHIEVED', 'REJECTED', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "MeasurementPlanStatus" AS ENUM ('ACTIVE', 'COMPLETED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "MeasurementCheckStatus" AS ENUM ('PENDING', 'SCHEDULED', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED');

-- CreateEnum
CREATE TYPE "AgencyTriggerType" AS ENUM ('SCHEDULE', 'USER_COMMAND', 'NEW_SIGNAL', 'NEW_EVIDENCE', 'COMPETITOR_CHANGE', 'SEO_CHANGE', 'MARKET_CHANGE', 'MEDIA_CHANGE', 'TREND_CHANGE', 'PERFORMANCE_CHANGE', 'TASK_COMPLETED', 'CAMPAIGN_COMPLETED', 'FOLLOW_UP_DUE', 'PROJECT_GOAL_CHANGED');

-- CreateEnum
CREATE TYPE "AgencyTriggerStatus" AS ENUM ('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', 'SKIPPED');

-- CreateEnum
CREATE TYPE "ApprovalLevel" AS ENUM ('LEVEL_0_AUTO_OBSERVE', 'LEVEL_1_INTERNAL_AUTOMATIC', 'LEVEL_2_AGENCY_DIRECTOR', 'LEVEL_3_CLIENT', 'LEVEL_4_CRITICAL');

-- CreateEnum
CREATE TYPE "BrandConstitutionStatus" AS ENUM ('DRAFT', 'ACTIVE', 'SUPERSEDED');

-- AlterEnum
-- AlterEnum

-- AlterEnum additions (must be committed before use as defaults)
ALTER TYPE "CapabilityKey" ADD VALUE 'PRODUCT_RESEARCH';
ALTER TYPE "CapabilityKey" ADD VALUE 'MEDIA_RESEARCH';
ALTER TYPE "CapabilityKey" ADD VALUE 'CULTURAL_RESEARCH';
ALTER TYPE "CapabilityKey" ADD VALUE 'CREATOR_RESEARCH';
ALTER TYPE "CapabilityKey" ADD VALUE 'PARTNERSHIP_RESEARCH';
ALTER TYPE "CapabilityKey" ADD VALUE 'ADVERTISING_RESEARCH';
ALTER TYPE "CapabilityKey" ADD VALUE 'REVIEW_RESEARCH';
ALTER TYPE "CapabilityKey" ADD VALUE 'TECHNOLOGY_RESEARCH';
ALTER TYPE "CapabilityKey" ADD VALUE 'SIGNAL_SCAN';
ALTER TYPE "CapabilityKey" ADD VALUE 'MEASUREMENT_CHECK';
ALTER TYPE "CapabilityKey" ADD VALUE 'WEBSITE_UPDATE';
ALTER TYPE "CapabilityKey" ADD VALUE 'PR_OUTREACH';
ALTER TYPE "OpportunityStatus" ADD VALUE 'EVALUATED';
ALTER TYPE "OpportunityStatus" ADD VALUE 'CONVERTED_TO_IDEA';
ALTER TYPE "OpportunityStatus" ADD VALUE 'EXPIRED';
ALTER TYPE "OpportunityStatus" ADD VALUE 'DUPLICATE';
